apiVersion: v1
kind: Service
metadata:
  name: my-web-server-service
  labels:
    app: my-web-server
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
  selector:
    app: my-web-server
