apiVersion: v1
kind: ReplicationController
metadata:
  name: my-web-server-rc
spec:
  replicas: 3
  selector:
    app: my-web-server
  template:
    metadata:
      name: my-web-server
      labels:
        app: my-web-server
    spec:
      containers: 
        - name: my-web-server
          image: kkeshavamurthy/alpine-nginx-for-kubernetes:v1
          ports:
            - containerPort: 80